### ISSUE TITLE
完成技能训练

### ISSUE THREAD

**Issue by apflu** [apflu/AllianceSimulator#4]
- [x] 完成Scheduler中跟踪技能训练队列的部分；(4806de19b5ed66ab9d6c07f6060dc2c04b049d65)
- [x] 支持向SkillUpdater中添加新的玩家，并保证线程安全；(848b6cf403f22c62888da3e0adf5cc51922e9bb3)
- [x] 在GameCharacter中将updateSkill方法的传入转接给SkillManager；
- [x] 在SkillManager中计算技能成长的量；
- [x] 记录技能成长；
- [x] 在技能等级满时发出提醒，并阻止技能点超过当前技能的训练上限。

**Comment by TsunemoriAkane** [comment]
https://github.com/apflu/AllianceSimulator/commit/1b6bc34b45753cda8932a7115f00e95edb9b0436
